#!/bin/sh
#
# Install the dpi framework programs inside the user's account.
#

BASE="$HOME/.dillo"
BASE2="$BASE/dpi"

if [ -r $BASE/dpi_socket_dir ] ; then
   rm -r `cat $BASE/dpi_socket_dir`
   rm $BASE/dpi_socket_dir
fi

if [ ! -x dpid/dpid ] ; then
   echo "This script may only be run AFTER make."
   exit 1
fi

# Try to communicate with any currently-running dpid to tell it
# to stop itself and the dpi programs.
dpidc stop

if [ ! -d $BASE ] ; then
  mkdir $BASE
fi
if [ ! -d $BASE2 ] ; then
  mkdir $BASE2
fi

cp dpid/dpid dpid/dpidc dpid/dpidrc $BASE
strip $BASE/dpid $BASE/dpidc

cd dpi
for F in *.dpi ; do
   D="`echo $F | sed 's/\..*$//'`"
   if [ ! -d $BASE2/$D ] ; then
      mkdir $BASE2/$D
   fi
   cp $F $BASE2/$D
   strip $BASE2/$D/$F
done
cd ..

